name = "miramunda-backend"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[placement]
mode = "smart"

[vars]

[observability]
enabled = true
