const n = null

// biome-ignore format: this is a map
export const MAP_68 = [
  // level 0
  [
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  1,  1,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  1,  1,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  7,  7,  8,  8,  9,  9,  n,  n, 10, 10, 11, 11, 12, 12,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  7,  7,  8,  8,  9,  9,  n,  n, 10, 10, 11, 11, 12, 12,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n, 13, 13, 14, 14, 15, 15, 16, 16,  n,  n, 17, 17, 18, 18, 19, 19, 20, 20,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n, 13, 13, 14, 14, 15, 15, 16, 16,  n,  n, 17, 17, 18, 18, 19, 19, 20, 20,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n, 21, 21, 22, 22, 23, 23, 24, 24,  n,  n, 25, 25, 26, 26, 27, 27, 28, 28,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n, 21, 21, 22, 22, 23, 23, 24, 24,  n,  n, 25, 25, 26, 26, 27, 27, 28, 28,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n, 29, 29, 30, 30, 31, 31,  n,  n, 32, 32, 33, 33, 34, 34,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n, 29, 29, 30, 30, 31, 31,  n,  n, 32, 32, 33, 33, 34, 34,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 40, 40,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 40, 40,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
  ],
  // level 1
  [
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 41, 41, 42, 42, 43, 43, 44, 44,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 41, 41, 42, 42, 43, 43, 44, 44,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 45, 45,  n,  n,  n,  n, 46, 46,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 45, 45,  n,  n,  n,  n, 46, 46,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n, 47, 47, 48, 48, 49, 49, 50, 50, 51, 51, 52, 52,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n, 47, 47, 48, 48, 49, 49, 50, 50, 51, 51, 52, 52,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n, 53, 53, 54, 54, 55, 55, 56, 56, 57, 57, 58, 58,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n, 53, 53, 54, 54, 55, 55, 56, 56, 57, 57, 58, 58,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n, 59, 59, 60, 60,  n,  n,  n,  n, 61, 61, 62, 62,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n, 59, 59, 60, 60,  n,  n,  n,  n, 61, 61, 62, 62,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 63, 63, 64, 64, 65, 65, 66, 66,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 63, 63, 64, 64, 65, 65, 66, 66,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
  ],
  // level 2
  [
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 67, 67,  n,  n,  n,  n, 68, 68,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n, 67, 67,  n,  n,  n,  n, 68, 68,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
  ],
  // level 3
  [
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
  ],
  // level 4
  [
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
    [  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n,  n],
  ]
]
